version: '3.8'

services:

  flask:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: flask-c
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 "catdog:app" --preload
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1000M
    networks:
      my-network:
        aliases:
          - flask-app

    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-c
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1000M
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - flask



networks:
  my-network:


